name: dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.19
  - dill
  - pip
  - numpy
  - pandas
  - opencv
  - h5py
  - hdf5
  - pip:
    - tensorflow==2.9.1
    - torch==2.3.1
    - torchvision==0.18.1
    - torchaudio==2.3.1
    - ultralytics==8.2.35
    - retina-face==0.0.17
    - pyinstaller==6.8.0